spring:
  profiles:
    active:
    - dev
eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      # eurekaServer设置了登录验证
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
---
spring:
  profiles: dev       # 开发环境
  application:
    name: springcloud-config-dev
server:
  port: 8201
---
spring:
  profiles: test      # 测试环境
  application:
    name: springcloud-config-test
server:
  port: 8202