spring:
  profiles:
  - dev
eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      # eurekaServer设置了登录验证
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
---
server:
  port: 8201
spring:
  profiles: dev
---
server:
  port: 8202
spring:
  profiles: test